"""DB_new_tables

Revision ID: 1c035a00f775
Revises: 
Create Date: 2023-12-20 16:41:02.254051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c035a00f775'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categor',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=100), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categor_title'), 'categor', ['title'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('categor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categor_id'], ['categor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_name'), 'staff', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_name'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_categor_title'), table_name='categor')
    op.drop_table('categor')
    # ### end Alembic commands ###
