"""empty message

Revision ID: e0c8d10059ba
Revises: aad1e1615399
Create Date: 2024-04-07 17:04:46.682422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c8d10059ba'
down_revision: Union[str, None] = 'aad1e1615399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_index('ix_staff_name', table_name='staff')
    op.drop_table('staff')
    op.drop_index('ix_categor_num', table_name='categor')
    op.drop_index('ix_categor_title', table_name='categor')
    op.drop_table('categor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categor',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=100, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('num', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categor_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_categor_title', 'categor', ['title'], unique=False)
    op.create_index('ix_categor_num', 'categor', ['num'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=10, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('categor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categor_id'], ['categor.id'], name='staff_categor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='staff_pkey')
    )
    op.create_index('ix_staff_name', 'staff', ['name'], unique=False)
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
